Restrict grpc version to <1.49.0 in PyFunc Server (#290)
<!--  Thanks for sending a pull request!  Here are some tips for you:

1. Run unit tests and ensure that they are passing
2. If your change introduces any API changes, make sure to update the
e2e tests
3. Make sure documentation is updated for your PR!

-->

**What this PR does / why we need it**:
<!-- Explain here the context and why you're making the change. What is
the problem you're trying to solve. --->
Starting version 1.49.0, grpc uses protobuf version 4.X which is
incompatible with most of our dependencies
(https://github.com/grpc/grpc/pull/30805) . This causes error while
building Pyfunc model:
```
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/aria/.local/share/virtualenvs/pyfunc-server-sOMOjTdZ/lib/python3.7/site-packages/google/protobuf/internal/__init__.py)
```


**Does this PR introduce a user-facing change?**:
<!--
If no, just write "NONE" in the release-note block below.
If yes, a release note is required. Enter your extended release note in
the block below.
If the PR requires additional action from users switching to the new
release, include the string "action required".

For more information about release notes, see kubernetes' guide here:
http://git.k8s.io/community/contributors/guide/release-notes.md
-->
NONE

**Checklist**

- [N.A.] Added unit test, integration, and/or e2e tests
- [x] Tested locally
- [N.A.] Updated documentation
- [N.A.] Update Swagger spec if the PR introduce API changes
- [N.A.] Regenerated Golang and Python client if the PR introduce API
changes