Release 0.14 (#167)
* Update swagger and clients

* Bump ui and sdk version to 0.14

* Fix build pyspark docker: AttributeError: 'FileNotFoundError' object has no attribute 'read'

Due to update in pip 21.2.2, the behavior on using requreiment file has changed. Read more: https://stackoverflow.com/a/68586065